replicaCount: 2

image:
  repository: ghcr.io/ldest/sre-course/api
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "f0135e1"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount: {}

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}

variables:
  ASPNETCORE_URLS: http://*:7777
  CONNECTIONSTRINGS__PGCONNECTION: server=77.105.185.111; port=7000; database=weather; username=sre-course-pgdb-user; password=my_password;

service:
  type: ClusterIP
  port: 7777

ingress:
  enabled: True
  className: "nginx"
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: weather-api.sre-course.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

autoscaling: {}
  #  enabled: false
  # minReplicas: 1
  # maxReplicas: 100
  # targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

volumes: []

volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}
