---
- name: Install dependences
  ansible.builtin.yum:
    name:
      - haproxy
    state: present

- name: Template config
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: "/etc/haproxy/haproxy.cfg"
    owner: root
    group: root
    mode: 0644
  notify: Reload haproxy

- name: Start haproxy service
  ansible.builtin.systemd:
    state: started
    name: haproxy
    enabled: true
