---
- name: Role for installing etcd
  hosts: etcd
  roles:
    - role: etcd

- name: Role for installing postgresql
  hosts: postgresql
  roles:
    - role: postgresql
    - role: patroni

- name: Role for instlling haproxy
  hosts: haproxy
  roles:
    - role: haproxy
