---
- name: Role for installing etcd
  hosts: etcd
  roles:
    - role: etcd
      tags: ["never", "etcd"]

- name: Role for installing postgresql
  hosts: postgresql
  roles:
    - role: postgresql
      tags: ["never", "postgresql"]
    
    - role: patroni
      tags: ["patroni"]
